---
 - name: restarting of apache2
   hosts: prod
   serial: 1
   tasks:
    - name: Gather service facts
      ansible.builtin.service:
        name: apache2
        state: restarted
      register: app

    - name: Display apache2 status
      ansible.builtin.debug:
        var: app
